version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: securitydb

    ports:
      - "5433:5432"  # Expose port for the database

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root@123
    ports:
      - "5050:80"  # Expose port for the pgAdmin web interface
